<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<strong>Please</strong> sign in' => 'لطفا <strong>وارد شوید</strong>',
  '<strong>Sign</strong> up' => '<strong>ثبت نام</strong>',
  'Create a new one.' => 'یکی دیگر ایجاد کنید.',
  'Don\'t have an account? Join the network by entering your e-mail address.' => 'حساب کاربری ندارید؟ با وارد کردن ایمیل خود به شبکه بپیوندید.',
  'Forgot your password?' => 'پسورد خود را فراموش کرده اید؟',
  'If you\'re already a member, please login with your username/email and password.' => 'اگر قبلا عضو شده اید، لطفا با نام کاربری/ایمیل و پسورد خود وارد شوید.',
  'Register' => 'ثبت نام',
  'Remember me next time' => 'مرا به خاطر بسپار',
  'Sign in' => 'ورود',
  'email' => 'ایمیل',
  'password' => 'پسورد',
  'username or email' => 'نام کاربری/ایمیل',
);
